version: "2.2"

networks:
  master_socialvoid:
    external: false
    ipam:
      config:
        - subnet: 172.16.57.0/24

services:

  rpc_server:
    image: socialvoid_rpc:dockerfile
    container_name: socialvoid_rpc
    restart: always
    hostname: socialvoid_rpc
    networks:
      - master_socialvoid
    depends_on:
      gearman:
        condition: "service_started"
      redis:
        condition: "service_started"
      mysql_master:
        condition: "service_healthy"
      mysql_slave:
        condition: "service_healthy"
      telegram_bot_api:
        condition: "service_started"
    volumes:
      - /var/socialvoid/config/acm:/etc/acm
      - /var/socialvoid/lib:/var/socialvoid/lib
      - /var/socialvoid/legal:/var/socialvoid/legal
      - /var/socialvoid/avatars:/var/socialvoid/avatars
      - /var/socialvoid/config/rpc_nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/socialvoid/config/rpc_socialvoid.conf:/etc/nginx/http.d/socialvoid_rpc.conf:ro
      - /var/socialvoid/config/rpc_supervisord.conf:/etc/supervisord.conf:ro
      - /var/socialvoid/logs/rpc_nginx:/var/log/nginx
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5200:5200"

  cdn_server:
    image: socialvoid_cdn:dockerfile
    container_name: socialvoid_cdn
    restart: always
    hostname: socialvoid_cdn
    networks:
      - master_socialvoid
    depends_on:
      gearman:
        condition: "service_started"
      redis:
        condition: "service_started"
      mysql_master:
        condition: "service_healthy"
      mysql_slave:
        condition: "service_healthy"
      telegram_bot_api:
        condition: "service_started"
    volumes:
      - /var/socialvoid/config/acm:/etc/acm
      - /var/socialvoid/lib:/var/socialvoid/lib
      - /var/socialvoid/legal:/var/socialvoid/legal
      - /var/socialvoid/avatars:/var/socialvoid/avatars
      - /var/socialvoid/config/cdn_nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/socialvoid/config/cdn_socialvoid.conf:/etc/nginx/http.d/socialvoid_cdn.conf:ro
      - /var/socialvoid/config/cdn_supervisord.conf:/etc/supervisord.conf:ro
      - /var/socialvoid/logs/cdn_nginx:/var/log/nginx
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5201:5201"

  mysql_master:
    image: mariadb:latest
    container_name: socialvoid_master_mysql
    hostname: master_mysql
    restart: unless-stopped
    networks:
      - master_socialvoid
    environment:
      MYSQL_DATABASE: socialvoid
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MYSQL_USER: socialvoid
      MYSQL_PASSWORD: socialvoid
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./build/master.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "master_mysql"]
      timeout: 20s
      retries: 10

  mysql_slave:
    image: mariadb:latest
    container_name: socialvoid_slave_mysql
    hostname: slave_mysql
    restart: unless-stopped
    networks:
      - master_socialvoid
    environment:
      MYSQL_DATABASE: socialvoid
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MYSQL_USER: socialvoid
      MYSQL_PASSWORD: socialvoid
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./build/slave.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "slave_mysql"]
      timeout: 20s
      retries: 10

  gearman_redis:
    image: redis:alpine
    container_name: socialvoid_gearmand_redis
    hostname: gearmand_redis
    networks:
      - master_socialvoid

  redis:
    image: redis:alpine
    container_name: socialvoid_redis
    hostname: redis
    networks:
      - master_socialvoid

  gearman:
    image: artefactual/gearmand:latest
    container_name: socialvoid_gearmand
    hostname: gearmand
    depends_on:
      - gearman_redis
    networks:
      - master_socialvoid
    environment:
      VERBOSE: ERROR
    command:
      - "--queue-type=redis"
      - "--redis-server=gearmand_redis"
      - "--redis-port=6379"

  telegram_bot_api:
    image: aiogram/telegram-bot-api:latest
    container_name: socialvoid_tdlib
    networks:
      - master_socialvoid
    environment:
      TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
      TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
      TELEGRAM_LOCAL: "1"
      TELEGRAM_STAT: "1"
    ports:
      - "5202:8081"
      - "5203:8082"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro