<?php

    /** @noinspection PhpUnused */

    namespace SocialvoidLib\Abstracts;

    /**
     * Class UserAuthenticationMethod
     * @package SocialvoidLib\Abstracts
     */
    abstract class UserAuthenticationMethod
    {
        /**
         * There is no authentication method available to this user,
         * this prevents authentication at all and might be used for bots
         * or strictly with an access token
         *
         * (For interpretation in the future, this leaves space for more ideas)
         */
        const None = "NONE";

        /**
         * The user uses a simple password to authenticate to the network
         */
        const Simple = "SIMPLE";

        /**
         * The user uses a simple password to authenticate to the network and
         * a one-time login code generated by a time-based authentication system
         * like Google Authenticator
         */
        const SimpleSecured = "SIMPLE_SECURED";

        /**
         * The user uses a CrossOverAuthentication provider to authenticate to the network
         */
        const CrossOverAuthentication = "COA";
    }