name: PPM Release Socialvoid Daemon

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release_daemon:
    runs-on: ubuntu-latest
    steps:

      - name: Add repoistory for PHP 8.0
        run: sudo add-apt-repository ppa:ondrej/php
      - name: Install PHP 8.0
        run: sudo apt-get install php8.0 php8.0-curl php8.0-mbstring php8.0-tokenizer php8.0-fileinfo

      - uses: actions/checkout@v2
        with:
          repository: intellivoid/ppm
          ref: "production"
          token: ${{ secrets.PPM_ACCESS_TOKEN }}
      - name: Install PPM
        run: sudo ./install
      - name: Configuring PPM
        run: sudo ppm --github-add-pat --alias="system" --token="${{ secrets.PPM_ACCESS_TOKEN }}"
      - uses: actions/checkout@master
      - name: Make build directory
        run: mkdir build

      - name: Prepare Socialvoid Daemon
        run: ppm --generate-package="src/Socialvoid"
      - name: Compile Socialvoid Daemon
        run: ppm --no-intro --verbose --compile="src/Socialvoid" --directory="build"
      - name: Install Socialvoid Daemon
        run: sudo -H ppm --no-prompt --fix-conflict --verbose --install="build/net.intellivoid.socialvoid.ppm"

      - name: Get Package Version
        run: echo package_version=$(ppm --get-version="build/net.intellivoid.socialvoid.ppm") >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/net.intellivoid.socialvoid.ppm
          name: "Socialvoid Daemon v${{ env.package_version }}"
          tag_name: "v${{ env.package_version }}"
          body: "Compiled PPM package for Socialvoid Daemon, version ${{ env.package_version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release_admin:
    runs-on: ubuntu-latest
    steps:

      - name: Add repoistory for PHP 8.0
        run: sudo add-apt-repository ppa:ondrej/php
      - name: Install PHP 8.0
        run: sudo apt-get install php8.0 php8.0-curl php8.0-mbstring php8.0-tokenizer php8.0-fileinfo

      - uses: actions/checkout@v2
        with:
          repository: intellivoid/ppm
          ref: "production"
          token: ${{ secrets.PPM_ACCESS_TOKEN }}
      - name: Install PPM
        run: sudo ./install
      - name: Configuring PPM
        run: sudo ppm --github-add-pat --alias="system" --token="${{ secrets.PPM_ACCESS_TOKEN }}"
      - uses: actions/checkout@master
      - name: Make build directory
        run: mkdir build

      - name: Prepare Socialvoid Admin
        run: ppm --generate-package="src/SocialvoidAdmin"
      - name: Compile Socialvoid Admin
        run: ppm --no-intro --verbose --compile="src/SocialvoidAdmin" --directory="build"
      - name: Install Socialvoid Admin
        run: sudo -H ppm --no-prompt --fix-conflict --verbose --install="build/net.intellivoid.socialvoid_admin.ppm"

      - name: Get Package Version
        run: echo package_version=$(ppm --get-version="build/net.intellivoid.socialvoid_admin.ppm") >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/net.intellivoid.socialvoid_admin.ppm
          name: "Socialvoid Admin v${{ env.package_version }}"
          tag_name: "v${{ env.package_version }}"
          body: "Compiled PPM package for Socialvoid Admin, version ${{ env.package_version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release_service:
    runs-on: ubuntu-latest
    steps:

      - name: Add repoistory for PHP 8.0
        run: sudo add-apt-repository ppa:ondrej/php
      - name: Install PHP 8.0
        run: sudo apt-get install php8.0 php8.0-curl php8.0-mbstring php8.0-tokenizer php8.0-fileinfo

      - uses: actions/checkout@v2
        with:
          repository: intellivoid/ppm
          ref: "production"
          token: ${{ secrets.PPM_ACCESS_TOKEN }}
      - name: Install PPM
        run: sudo ./install
      - name: Configuring PPM
        run: sudo ppm --github-add-pat --alias="system" --token="${{ secrets.PPM_ACCESS_TOKEN }}"
      - uses: actions/checkout@master
      - name: Make build directory
        run: mkdir build

      - name: Prepare SocialvoidService
        run: ppm --generate-package="src/SocialvoidService"
      - name: Compile SocialvoidService
        run: ppm --no-intro --verbose --compile="src/SocialvoidService" --directory="build"
      - name: Install SocialvoidService
        run: sudo -H ppm --no-prompt --fix-conflict --verbose --install="build/net.intellivoid.socialvoid_service.ppm"

      - name: Get Package Version
        run: echo package_version=$(ppm --get-version="build/net.intellivoid.socialvoid_service.ppm") >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/net.intellivoid.socialvoid_service.ppm
          name: "SocialvoidService v${{ env.package_version }}"
          tag_name: "v${{ env.package_version }}"
          body: "Compiled PPM package for SocialvoidService, version ${{ env.package_version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release_lib:
    runs-on: ubuntu-latest
    steps:

      - name: Add repoistory for PHP 8.0
        run: sudo add-apt-repository ppa:ondrej/php
      - name: Install PHP 8.0
        run: sudo apt-get install php8.0 php8.0-curl php8.0-mbstring php8.0-tokenizer php8.0-fileinfo

      - uses: actions/checkout@v2
        with:
          repository: intellivoid/ppm
          ref: "production"
          token: ${{ secrets.PPM_ACCESS_TOKEN }}
      - name: Install PPM
        run: sudo ./install
      - name: Configuring PPM
        run: sudo ppm --github-add-pat --alias="system" --token="${{ secrets.PPM_ACCESS_TOKEN }}"
      - uses: actions/checkout@master
      - name: Make build directory
        run: mkdir build

      - name: Prepare SocialvoidLib
        run: ppm --generate-package="src/SocialvoidLib"
      - name: Compile SocialvoidLib
        run: ppm --no-intro --verbose --compile="src/SocialvoidLib" --directory="build"
      - name: Install SocialvoidLib
        run: sudo -H ppm --no-prompt --fix-conflict --verbose --install="build/net.intellivoid.socialvoidlib.ppm"

      - name: Get Package Version
        run: echo package_version=$(ppm --get-version="build/net.intellivoid.socialvoidlib.ppm") >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/net.intellivoid.socialvoidlib.ppm
          name: "SocialvoidLib v${{ env.package_version }}"
          tag_name: "v${{ env.package_version }}"
          body: "Compiled PPM package for SocialvoidLib, version ${{ env.package_version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}