name: PPM CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Add repoistory for PHP 8.0
      run: sudo add-apt-repository ppa:ondrej/php
    - name: Install PHP 8.0
      run: sudo apt-get install php8.0 php8.0-curl php8.0-mbstring php8.0-tokenizer php8.0-fileinfo

    - uses: actions/checkout@v2
      with:
        repository: intellivoid/ppm
        ref: "production"
        token: ${{ secrets.PPM_ACCESS_TOKEN }}
    - name: Install PPM
      run: sudo ./install
    - name: Configuring PPM
      run: sudo ppm --github-add-pat --alias="system" --token="${{ secrets.PPM_ACCESS_TOKEN }}"
    - uses: actions/checkout@master
    - name: Make build directory
      run: mkdir build

    - name: Prepare SocialvoidLib
      run: ppm --generate-package="src/SocialvoidLib"
    - name: Compile SocialvoidLib
      run: ppm --no-intro --verbose --compile="src/SocialvoidLib" --directory="build"
    - name: Install SocialvoidLib
      run: sudo -H ppm --no-prompt --fix-conflict --verbose --install="build/net.intellivoid.socialvoidlib.ppm" --branch="production"

    - name: Prepare SocialvoidService
      run: ppm --generate-package="src/SocialvoidService"
    - name: Compile SocialvoidService
      run: ppm --no-intro --verbose --compile="src/SocialvoidService" --directory="build"
    - name: Install SocialvoidService
      run: sudo -H ppm --no-prompt --fix-conflict --verbose --install="build/net.intellivoid.socialvoid_service.ppm" --branch="production"

    - name: Prepare SocialvoidRPC
      run: ppm --generate-package="src/SocialvoidRPC"
    - name: Compile SocialvoidRPC
      run: ppm --no-intro --verbose --compile="src/SocialvoidRPC" --directory="build"
    - name: Install SocialvoidRPC
      run: sudo -H ppm --no-prompt --fix-conflict --verbose --install="build/net.intellivoid.socialvoid_rpc.ppm" --branch="production"

    - name: Prepare SocialvoidAdmin
      run: ppm --generate-package="src/SocialvoidAdmin"
    - name: Compile SocialvoidAdmin
      run: ppm --no-intro --verbose --compile="src/SocialvoidAdmin" --directory="build"
    - name: Install SocialvoidAdmin
      run: sudo -H ppm --no-prompt --fix-conflict --verbose --install="build/net.intellivoid.socialvoid_admin.ppm" --branch="production"

    - name: Prepare Socialvoid
      run: ppm --generate-package="src/Socialvoid"
    - name: Compile Socialvoid
      run: ppm --no-intro --verbose --compile="src/Socialvoid" --directory="build"
    - name: Install Socialvoid
      run: sudo -H ppm --no-prompt --fix-conflict --verbose --install="build/net.intellivoid.socialvoid.ppm" --branch="production"