name: PPM CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: intellivoid/ppm
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Install Software-Properties-Common
      run: sudo apt install software-properties-common
    - name: Add repoistory
      run: sudo add-apt-repository ppa:ondrej/php
    - name: Install PHP 8.0
      run: sudo apt-get install php8.0 php-pear8.0 php-curl8.0 php-mbstring8.0 php-tokenizer8.0 php-fileinfo8.0
