name: PPM CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Software-Properties-Common
      run: sudo apt install software-properties-common
    - name: Add repoistory
      run: sudo add-apt-repository ppa:ondrej/php
    - name: Install PHP 8.0
      run: sudo apt-get install php8.0 php8.0-curl php8.0-mbstring php8.0-tokenizer php8.0-fileinfo
    - uses: actions/checkout@8.0
      with:
        repository: intellivoid/ppm
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Install PPM
      run: sudo ./install
    - name: Configuring PPM
      run: sudo ppm --github-add-pat --alias="system" --token="${{ secrets.ACCESS_TOKEN }}"
    - uses: actions/checkout@master
    - name: Compiling
      run: make build
